// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rviqvqbohxpkbxrwtwwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2aXF2cWJvaHhwa2J4cnd0d3dlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NzgzNTIsImV4cCI6MjA2NjQ1NDM1Mn0.12gnKEfLRdpUifbm-C8k4J6Y8gjvd9LChu-ydeKQfdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);